/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import { useLayoutEffect, useRef } from 'react'
import { useGLTF, CubeCamera } from '@react-three/drei'

import Porsche from "./porsche.glb"

export default function Model({ ...props }) {
  const group = useRef()
  //const { nodes, materials } = useGLTF(Prosche)

  const model = useGLTF(Porsche)
  
  useLayoutEffect(() => {
    model.materials.paint.color.set('#ff00ff')
    model.materials.paint.metalness = 0.2
    model.materials.paint.roughness = 0
    model.materials.paint.clearcoat = 1
    model.materials.paint.envMapIntensity = 1.5
    model.materials.paint.aoMapIntensity = 1.5
    model.materials.paint.roughnessMapIntensity = 2
    model.materials['930_chromes'].metalness = 1
    model.materials['930_chromes'].roughness = 0.3
    model.materials['930_chromes'].color = new THREE.Color('white')
    model.materials['glass'].color = new THREE.Color('white')
    model.materials['glass'].opacity = 0.6
    model.materials['930_plastics'].roughness = 0.8
    model.materials['930_lights'].emissiveMap = model.materials['930_lights'].map
    model.materials['930_lights'].emissiveIntensity = 50
    model.materials['930_tire'].color.set('black')
    model.materials['930_tire'].roughness = 0.7
  }, [model.materials])

  return (
    <group ref={group} {...props} dispose={null}>
      <CubeCamera frames={1} position={[0, 1.5, 0]} near={0.1} resolution={128}>
        {(texture) => (
          <group position={[0, -1.5, 0]}>
            <group rotation={[Math.PI / 2, 0, 0]}>
              <mesh
                geometry={model.nodes.mesh_1_instance_0.geometry}
                material={model.materials['930_plastics']}
                position={[-7.966238, -0.10155, -7.966238]}
                scale={0.000973}
              />
              <mesh
                geometry={model.nodes.mesh_1_instance_1.geometry}
                material={model.materials['930_plastics']}
                position={[-7.966238, -0.10155, -7.966238]}
                scale={0.000973}
              />
            </group>
            <group position={[-7.966238, -0.10155, -7.966238]} scale={0.000973}>
              <mesh geometry={model.nodes.mesh_0.geometry} material={model.materials.paint} material-envMap={texture} />
              <mesh geometry={model.nodes.mesh_0_1.geometry} material={model.materials['930_chromes']} />
              <mesh geometry={model.nodes.mesh_0_2.geometry} material={model.materials.black} />
              <mesh geometry={model.nodes.mesh_0_3.geometry} material={model.materials['930_lights']} />
              <mesh geometry={model.nodes.mesh_0_4.geometry} material={model.materials.glass} />
              <mesh geometry={model.nodes.mesh_0_5.geometry} material={model.materials['930_stickers']} />
              <mesh geometry={model.nodes.mesh_0_6.geometry} material={model.materials['930_plastics']} material-polygonOffset material-polygonOffsetFactor={-10} />
              <mesh geometry={model.nodes.mesh_0_7.geometry} material={model.materials['930_lights_refraction']} />
              <mesh geometry={model.nodes.mesh_0_8.geometry} material={model.materials['930_rim']} />
              <mesh geometry={model.nodes.mesh_0_9.geometry} material={model.materials['930_tire']} />
            </group>
          </group>
        )}
      </CubeCamera>
    </group>
  )
}

useGLTF.preload(Porsche)
